### PR TITLE
Modular imports

### PR DESCRIPTION
**Pull request by manuelmeister**
Added possibility to import only certain `@font-face`s

### CODE REVIEW

**Comment by philipbelesky** [comment]
Hey @manuelmeister, thanks for adding this. My knowledge of working with sass imports/modules is relatively rudimentary (I don't do a heap of front-end anymore) so happy to defer to what looks to be a very clean setup. 

If you had the time, it would be great to add a further section to `README.md` that would quickly detail how to import the face at a given weight. This would help highlight that the package supports this and also help people who are unfamiliar with this style of import. If you didn't have the time for this let me know and I can merge the PR regardless.

**Comment by manuelmeister** [comment]
Okay, I explained the weight selection in `README.md`
I also added fonts with a latin characters subset. With this optimization the font filesizes are a fifth the size.

**Comment by philipbelesky** [comment]
Great, thanks so much for adding this. Would you like some sort of credit line in the `README`?

Also, with regards to the latin subset, can the extraction process be automated? This is a valuable addition but I'd like to be able to repeat the process when the upstream repo updates.

**Comment by manuelmeister** [comment]
What’s your existing process?

**Comment by philipbelesky** [comment]
I haven't extracted the latin subsets before — I assume there is a tool for doing so easily?

Upon a new release to the main Inter repo I just copy over the new font files and reconcile any css changes manually.

**Comment by manuelmeister** [comment]
Yes, I had added it to the `README.md`:

The tool is called [glyphhanger](https://github.com/filamentgroup/glyphhanger). I've copied the *.otf font files from the folder `Inter` of the main repo to the `Inter (web latin)` folder. Then I used the following command to convert the *.otf font files to woff and woff2:

 ```glyphhanger --subset="*.otf" --LATIN --formats=woff,woff2```

This generates all fonts in the desired format with the filename-ending 
`-subset.woff` and `-subset.woff2`
Finally, I rename all woff and woff2 fonts.
(I use the macOS rename dialog and replace `-subset` with empty.)

**Comment by manuelmeister** [comment]
BTW: Can you please update NPM? :)

**Comment by manuelmeister** [comment]
Can you please publish the newest version to npm?
It would be nice to be a contributor in the package.json:
```json
{
"name":"Manuel Meister",
"email":"manuel@meister.id"
"url":"https://meister.id"
}
```

**Comment by philipbelesky** [comment]
Sorry, I managed to miss that part at the bottom of the README changes. I've pushed up a new release — somewhat awkwardly as a hotfix increment as major/minor versions track the main repo. Thanks again!

**Pull request merged**
